// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apis.proto

package mppbs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// output any
type ApiResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *any.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiResponse) Reset()         { *m = ApiResponse{} }
func (m *ApiResponse) String() string { return proto.CompactTextString(m) }
func (*ApiResponse) ProtoMessage()    {}
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{0}
}

func (m *ApiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiResponse.Unmarshal(m, b)
}
func (m *ApiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiResponse.Marshal(b, m, deterministic)
}
func (m *ApiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiResponse.Merge(m, src)
}
func (m *ApiResponse) XXX_Size() int {
	return xxx_messageInfo_ApiResponse.Size(m)
}
func (m *ApiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiResponse proto.InternalMessageInfo

func (m *ApiResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ApiResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ApiResponse) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

// 登录信息
type LoginInfo struct {
	Authorization        string      `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	Menus                []*MenuItem `protobuf:"bytes,2,rep,name=menus,proto3" json:"menus,omitempty"`
	UserInfo             *UserInfo   `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginInfo) Reset()         { *m = LoginInfo{} }
func (m *LoginInfo) String() string { return proto.CompactTextString(m) }
func (*LoginInfo) ProtoMessage()    {}
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{1}
}

func (m *LoginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfo.Unmarshal(m, b)
}
func (m *LoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfo.Marshal(b, m, deterministic)
}
func (m *LoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfo.Merge(m, src)
}
func (m *LoginInfo) XXX_Size() int {
	return xxx_messageInfo_LoginInfo.Size(m)
}
func (m *LoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfo proto.InternalMessageInfo

func (m *LoginInfo) GetAuthorization() string {
	if m != nil {
		return m.Authorization
	}
	return ""
}

func (m *LoginInfo) GetMenus() []*MenuItem {
	if m != nil {
		return m.Menus
	}
	return nil
}

func (m *LoginInfo) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type UserInfo struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// 菜单项
type MenuItem struct {
	Id                   int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MenuKey              string      `protobuf:"bytes,2,opt,name=menu_key,json=menuKey,proto3" json:"menu_key,omitempty"`
	Level                int32       `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	DisplayOrder         int32       `protobuf:"varint,4,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	Path                 string      `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Component            string      `protobuf:"bytes,6,opt,name=component,proto3" json:"component,omitempty"`
	Redirect             string      `protobuf:"bytes,7,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Name                 string      `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Title                string      `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	Icon                 string      `protobuf:"bytes,10,opt,name=icon,proto3" json:"icon,omitempty"`
	BasePath             string      `protobuf:"bytes,11,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	Children             []*MenuItem `protobuf:"bytes,12,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MenuItem) Reset()         { *m = MenuItem{} }
func (m *MenuItem) String() string { return proto.CompactTextString(m) }
func (*MenuItem) ProtoMessage()    {}
func (*MenuItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{3}
}

func (m *MenuItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuItem.Unmarshal(m, b)
}
func (m *MenuItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuItem.Marshal(b, m, deterministic)
}
func (m *MenuItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuItem.Merge(m, src)
}
func (m *MenuItem) XXX_Size() int {
	return xxx_messageInfo_MenuItem.Size(m)
}
func (m *MenuItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuItem.DiscardUnknown(m)
}

var xxx_messageInfo_MenuItem proto.InternalMessageInfo

func (m *MenuItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MenuItem) GetMenuKey() string {
	if m != nil {
		return m.MenuKey
	}
	return ""
}

func (m *MenuItem) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *MenuItem) GetDisplayOrder() int32 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *MenuItem) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *MenuItem) GetComponent() string {
	if m != nil {
		return m.Component
	}
	return ""
}

func (m *MenuItem) GetRedirect() string {
	if m != nil {
		return m.Redirect
	}
	return ""
}

func (m *MenuItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MenuItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MenuItem) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *MenuItem) GetBasePath() string {
	if m != nil {
		return m.BasePath
	}
	return ""
}

func (m *MenuItem) GetChildren() []*MenuItem {
	if m != nil {
		return m.Children
	}
	return nil
}

// 菜单
type Menu struct {
	Items                []*MenuItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Menu) Reset()         { *m = Menu{} }
func (m *Menu) String() string { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()    {}
func (*Menu) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{4}
}

func (m *Menu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menu.Unmarshal(m, b)
}
func (m *Menu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menu.Marshal(b, m, deterministic)
}
func (m *Menu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menu.Merge(m, src)
}
func (m *Menu) XXX_Size() int {
	return xxx_messageInfo_Menu.Size(m)
}
func (m *Menu) XXX_DiscardUnknown() {
	xxx_messageInfo_Menu.DiscardUnknown(m)
}

var xxx_messageInfo_Menu proto.InternalMessageInfo

func (m *Menu) GetItems() []*MenuItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// 权限树
type Power struct {
	Items                []*PowerItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Power) Reset()         { *m = Power{} }
func (m *Power) String() string { return proto.CompactTextString(m) }
func (*Power) ProtoMessage()    {}
func (*Power) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{5}
}

func (m *Power) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Power.Unmarshal(m, b)
}
func (m *Power) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Power.Marshal(b, m, deterministic)
}
func (m *Power) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Power.Merge(m, src)
}
func (m *Power) XXX_Size() int {
	return xxx_messageInfo_Power.Size(m)
}
func (m *Power) XXX_DiscardUnknown() {
	xxx_messageInfo_Power.DiscardUnknown(m)
}

var xxx_messageInfo_Power proto.InternalMessageInfo

func (m *Power) GetItems() []*PowerItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// 权限项
type PowerItem struct {
	MenuKey              string       `protobuf:"bytes,1,opt,name=menu_key,json=menuKey,proto3" json:"menu_key,omitempty"`
	Level                int32        `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	DisplayOrder         int32        `protobuf:"varint,3,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	Name                 string       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Title                string       `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Selected             bool         `protobuf:"varint,6,opt,name=selected,proto3" json:"selected,omitempty"`
	Children             []*PowerItem `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PowerItem) Reset()         { *m = PowerItem{} }
func (m *PowerItem) String() string { return proto.CompactTextString(m) }
func (*PowerItem) ProtoMessage()    {}
func (*PowerItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{6}
}

func (m *PowerItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PowerItem.Unmarshal(m, b)
}
func (m *PowerItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PowerItem.Marshal(b, m, deterministic)
}
func (m *PowerItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PowerItem.Merge(m, src)
}
func (m *PowerItem) XXX_Size() int {
	return xxx_messageInfo_PowerItem.Size(m)
}
func (m *PowerItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PowerItem.DiscardUnknown(m)
}

var xxx_messageInfo_PowerItem proto.InternalMessageInfo

func (m *PowerItem) GetMenuKey() string {
	if m != nil {
		return m.MenuKey
	}
	return ""
}

func (m *PowerItem) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *PowerItem) GetDisplayOrder() int32 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *PowerItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PowerItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PowerItem) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

func (m *PowerItem) GetChildren() []*PowerItem {
	if m != nil {
		return m.Children
	}
	return nil
}

type UserAdminInfo struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	RoleKey              string   `protobuf:"bytes,4,opt,name=role_key,json=roleKey,proto3" json:"role_key,omitempty"`
	Roles                []string `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	IsAdmin              int32    `protobuf:"varint,6,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Admin                string   `protobuf:"bytes,7,opt,name=admin,proto3" json:"admin,omitempty"`
	CreateTime           int32    `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int32    `protobuf:"varint,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAdminInfo) Reset()         { *m = UserAdminInfo{} }
func (m *UserAdminInfo) String() string { return proto.CompactTextString(m) }
func (*UserAdminInfo) ProtoMessage()    {}
func (*UserAdminInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{7}
}

func (m *UserAdminInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAdminInfo.Unmarshal(m, b)
}
func (m *UserAdminInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAdminInfo.Marshal(b, m, deterministic)
}
func (m *UserAdminInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAdminInfo.Merge(m, src)
}
func (m *UserAdminInfo) XXX_Size() int {
	return xxx_messageInfo_UserAdminInfo.Size(m)
}
func (m *UserAdminInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAdminInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserAdminInfo proto.InternalMessageInfo

func (m *UserAdminInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserAdminInfo) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserAdminInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserAdminInfo) GetRoleKey() string {
	if m != nil {
		return m.RoleKey
	}
	return ""
}

func (m *UserAdminInfo) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *UserAdminInfo) GetIsAdmin() int32 {
	if m != nil {
		return m.IsAdmin
	}
	return 0
}

func (m *UserAdminInfo) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *UserAdminInfo) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *UserAdminInfo) GetUpdateTime() int32 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type UserList struct {
	Page                 int32            `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32            `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	TotalPage            int32            `protobuf:"varint,3,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	TotalSize            int32            `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	List                 []*UserAdminInfo `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{8}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserList) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *UserList) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *UserList) GetTotalSize() int32 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *UserList) GetList() []*UserAdminInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type Role struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	RoleKey              string   `protobuf:"bytes,4,opt,name=role_key,json=roleKey,proto3" json:"role_key,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	StatusDesc           string   `protobuf:"bytes,6,opt,name=status_desc,json=statusDesc,proto3" json:"status_desc,omitempty"`
	CreateTime           int32    `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int32    `protobuf:"varint,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{9}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Role) GetRoleKey() string {
	if m != nil {
		return m.RoleKey
	}
	return ""
}

func (m *Role) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Role) GetStatusDesc() string {
	if m != nil {
		return m.StatusDesc
	}
	return ""
}

func (m *Role) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Role) GetUpdateTime() int32 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type RoleList struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	TotalPage            int32    `protobuf:"varint,3,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	TotalSize            int32    `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	List                 []*Role  `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleList) Reset()         { *m = RoleList{} }
func (m *RoleList) String() string { return proto.CompactTextString(m) }
func (*RoleList) ProtoMessage()    {}
func (*RoleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{10}
}

func (m *RoleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleList.Unmarshal(m, b)
}
func (m *RoleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleList.Marshal(b, m, deterministic)
}
func (m *RoleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleList.Merge(m, src)
}
func (m *RoleList) XXX_Size() int {
	return xxx_messageInfo_RoleList.Size(m)
}
func (m *RoleList) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleList.DiscardUnknown(m)
}

var xxx_messageInfo_RoleList proto.InternalMessageInfo

func (m *RoleList) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RoleList) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RoleList) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *RoleList) GetTotalSize() int32 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *RoleList) GetList() []*Role {
	if m != nil {
		return m.List
	}
	return nil
}

type RolePowerMultiAddResult struct {
	Ids                  []int32  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RolePowerMultiAddResult) Reset()         { *m = RolePowerMultiAddResult{} }
func (m *RolePowerMultiAddResult) String() string { return proto.CompactTextString(m) }
func (*RolePowerMultiAddResult) ProtoMessage()    {}
func (*RolePowerMultiAddResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{11}
}

func (m *RolePowerMultiAddResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolePowerMultiAddResult.Unmarshal(m, b)
}
func (m *RolePowerMultiAddResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolePowerMultiAddResult.Marshal(b, m, deterministic)
}
func (m *RolePowerMultiAddResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolePowerMultiAddResult.Merge(m, src)
}
func (m *RolePowerMultiAddResult) XXX_Size() int {
	return xxx_messageInfo_RolePowerMultiAddResult.Size(m)
}
func (m *RolePowerMultiAddResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RolePowerMultiAddResult.DiscardUnknown(m)
}

var xxx_messageInfo_RolePowerMultiAddResult proto.InternalMessageInfo

func (m *RolePowerMultiAddResult) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiResponse)(nil), "mppbs.ApiResponse")
	proto.RegisterType((*LoginInfo)(nil), "mppbs.LoginInfo")
	proto.RegisterType((*UserInfo)(nil), "mppbs.UserInfo")
	proto.RegisterType((*MenuItem)(nil), "mppbs.MenuItem")
	proto.RegisterType((*Menu)(nil), "mppbs.Menu")
	proto.RegisterType((*Power)(nil), "mppbs.Power")
	proto.RegisterType((*PowerItem)(nil), "mppbs.PowerItem")
	proto.RegisterType((*UserAdminInfo)(nil), "mppbs.UserAdminInfo")
	proto.RegisterType((*UserList)(nil), "mppbs.UserList")
	proto.RegisterType((*Role)(nil), "mppbs.Role")
	proto.RegisterType((*RoleList)(nil), "mppbs.RoleList")
	proto.RegisterType((*RolePowerMultiAddResult)(nil), "mppbs.RolePowerMultiAddResult")
}

func init() {
	proto.RegisterFile("apis.proto", fileDescriptor_b480fce41873d8e6)
}

var fileDescriptor_b480fce41873d8e6 = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcd, 0x6e, 0xe4, 0x44,
	0x10, 0x96, 0x3d, 0x76, 0xc6, 0xae, 0xd9, 0xc0, 0xaa, 0xb5, 0x02, 0x6f, 0x00, 0xed, 0xc8, 0xfc,
	0x68, 0xa4, 0x5d, 0x26, 0xd2, 0xf2, 0x04, 0x23, 0xc1, 0x21, 0x22, 0x81, 0xa8, 0x81, 0x23, 0xb2,
	0x3c, 0x76, 0x65, 0xd2, 0xc2, 0x76, 0x5b, 0xee, 0x36, 0x68, 0xf2, 0x00, 0xdc, 0xb9, 0xf2, 0x40,
	0x3c, 0x01, 0xbc, 0x0e, 0x42, 0x55, 0xed, 0x71, 0x66, 0xf2, 0xc7, 0x6d, 0x6f, 0x55, 0x5f, 0x57,
	0x95, 0xab, 0xbe, 0xaf, 0xba, 0x0d, 0x90, 0xb7, 0xca, 0x2c, 0xdb, 0x4e, 0x5b, 0x2d, 0xc2, 0xba,
	0x6d, 0xd7, 0xe6, 0xe4, 0xe5, 0x46, 0xeb, 0x4d, 0x85, 0xa7, 0x0c, 0xae, 0xfb, 0xab, 0xd3, 0xbc,
	0xd9, 0xba, 0x88, 0xf4, 0x67, 0x98, 0xad, 0x5a, 0x25, 0xd1, 0xb4, 0xba, 0x31, 0x28, 0x04, 0x04,
	0x85, 0x2e, 0x31, 0xf1, 0xe6, 0xde, 0x22, 0x94, 0x6c, 0x8b, 0xe7, 0x30, 0xa9, 0xcd, 0x26, 0xf1,
	0xe7, 0xde, 0x22, 0x96, 0x64, 0x8a, 0x05, 0x04, 0x65, 0x6e, 0xf3, 0x64, 0x32, 0xf7, 0x16, 0xb3,
	0xb7, 0x2f, 0x96, 0xae, 0xfc, 0x72, 0x57, 0x7e, 0xb9, 0x6a, 0xb6, 0x92, 0x23, 0xd2, 0xdf, 0x3d,
	0x88, 0xcf, 0xf5, 0x46, 0x35, 0x67, 0xcd, 0x95, 0x16, 0x9f, 0xc1, 0x71, 0xde, 0xdb, 0x6b, 0xdd,
	0xa9, 0x9b, 0xdc, 0x2a, 0xdd, 0xf0, 0x67, 0x62, 0x79, 0x08, 0x8a, 0xcf, 0x21, 0xac, 0xb1, 0xe9,
	0x4d, 0xe2, 0xcf, 0x27, 0x8b, 0xd9, 0xdb, 0xf7, 0x97, 0x3c, 0xc4, 0xf2, 0x02, 0x9b, 0xfe, 0xcc,
	0x62, 0x2d, 0xdd, 0xa9, 0x78, 0x03, 0x71, 0x6f, 0xb0, 0xcb, 0x54, 0x73, 0xa5, 0x87, 0x4e, 0x76,
	0xa1, 0x3f, 0x19, 0xec, 0xe8, 0x83, 0x32, 0xea, 0x07, 0x2b, 0xfd, 0x06, 0xa2, 0x1d, 0x2a, 0x3e,
	0x01, 0xa8, 0xa8, 0xa7, 0xac, 0xc9, 0x6b, 0x1c, 0x7a, 0x88, 0x19, 0xf9, 0x2e, 0xaf, 0x51, 0x9c,
	0x00, 0xa7, 0xf1, 0xa1, 0x1b, 0x7a, 0xf4, 0xd3, 0xbf, 0x7c, 0x88, 0x76, 0x8d, 0x88, 0xf7, 0xc0,
	0x57, 0xe5, 0x40, 0x95, 0xaf, 0x4a, 0xf1, 0x12, 0x22, 0x6a, 0x2d, 0xfb, 0x05, 0xb7, 0x43, 0xe2,
	0x94, 0xfc, 0x6f, 0x71, 0x2b, 0x5e, 0x40, 0x58, 0xe1, 0xaf, 0x58, 0x71, 0xa3, 0xa1, 0x74, 0x8e,
	0xf8, 0x14, 0x8e, 0x4b, 0x65, 0xda, 0x2a, 0xdf, 0x66, 0xba, 0x2b, 0xb1, 0x4b, 0x02, 0x3e, 0x7d,
	0x36, 0x80, 0xdf, 0x13, 0x46, 0x92, 0xb4, 0xb9, 0xbd, 0x4e, 0x42, 0xae, 0xc8, 0xb6, 0xf8, 0x18,
	0xe2, 0x42, 0xd7, 0xad, 0x6e, 0xb0, 0xb1, 0xc9, 0x91, 0x1b, 0x60, 0x04, 0x68, 0x80, 0x0e, 0x4b,
	0xd5, 0x61, 0x61, 0x93, 0xa9, 0x1b, 0x60, 0xe7, 0x53, 0x35, 0x1e, 0x2c, 0x72, 0xd5, 0xc8, 0xa6,
	0xe6, 0xac, 0xb2, 0x15, 0x26, 0x31, 0x83, 0xce, 0xa1, 0x48, 0x55, 0xe8, 0x26, 0x01, 0x17, 0x49,
	0xb6, 0xf8, 0x08, 0xe2, 0x75, 0x6e, 0x30, 0xe3, 0x86, 0x66, 0xae, 0x34, 0x01, 0x97, 0xd4, 0xd4,
	0x6b, 0x88, 0x8a, 0x6b, 0x55, 0x95, 0x1d, 0x36, 0xc9, 0xb3, 0x87, 0xa5, 0x1b, 0x03, 0xd2, 0x2f,
	0x21, 0x20, 0x94, 0xc4, 0x56, 0x16, 0x6b, 0x93, 0x78, 0x8f, 0x88, 0xcd, 0xa7, 0xe9, 0x29, 0x84,
	0x97, 0xfa, 0x37, 0xec, 0xc4, 0x17, 0x87, 0xf1, 0xcf, 0x87, 0x78, 0x3e, 0xdc, 0x4f, 0xf8, 0xc7,
	0x83, 0x78, 0x04, 0x0f, 0x94, 0xf1, 0x1e, 0x51, 0xc6, 0x7f, 0x52, 0x99, 0xc9, 0xc3, 0xca, 0x30,
	0x97, 0xc1, 0x43, 0x5c, 0x86, 0xfb, 0x5c, 0x9e, 0x40, 0x64, 0xb0, 0xc2, 0xc2, 0x62, 0xc9, 0x72,
	0x45, 0x72, 0xf4, 0xc5, 0x9b, 0x3d, 0xda, 0xa6, 0x8f, 0x0c, 0x75, 0xcb, 0xdb, 0xbf, 0x1e, 0x1c,
	0xd3, 0x22, 0xaf, 0xca, 0x7a, 0xb8, 0x54, 0x77, 0xb7, 0xf0, 0x70, 0xbb, 0xfd, 0xa7, 0xb6, 0x7b,
	0x72, 0xb8, 0xdd, 0x44, 0x53, 0xa7, 0x2b, 0x64, 0x9a, 0xdc, 0x50, 0x53, 0xf2, 0x07, 0x9a, 0xc8,
	0x34, 0x49, 0x38, 0x9f, 0xd0, 0x5c, 0xec, 0x50, 0x82, 0x32, 0x59, 0x4e, 0xbd, 0xf0, 0x5c, 0xa1,
	0x9c, 0x2a, 0xc3, 0xad, 0x51, 0x82, 0xc3, 0xdd, 0x06, 0x3a, 0x47, 0xbc, 0x82, 0x59, 0xd1, 0x61,
	0x6e, 0x31, 0xb3, 0x6a, 0xd8, 0xc2, 0x50, 0x82, 0x83, 0x7e, 0x54, 0x35, 0x52, 0x40, 0xdf, 0x96,
	0x63, 0x40, 0xec, 0x02, 0x1c, 0x44, 0x01, 0xe9, 0x9f, 0x9e, 0xbb, 0xc9, 0xe7, 0xca, 0x58, 0x77,
	0x37, 0x36, 0xe3, 0x73, 0x45, 0x36, 0x61, 0x46, 0xdd, 0xe0, 0xa0, 0x27, 0xdb, 0xc4, 0x89, 0xd5,
	0x36, 0xaf, 0x32, 0x8e, 0x76, 0x5a, 0xc6, 0x8c, 0x5c, 0x52, 0xca, 0x78, 0xcc, 0x89, 0xc1, 0xde,
	0xf1, 0x0f, 0x94, 0xbd, 0x80, 0xa0, 0x52, 0xc6, 0xf2, 0xe8, 0xf4, 0xdc, 0xdd, 0x3e, 0x32, 0xa3,
	0x0a, 0x92, 0x23, 0xd2, 0xbf, 0x3d, 0x08, 0xa4, 0xae, 0xf0, 0x9e, 0x28, 0xbb, 0x55, 0xf1, 0xf7,
	0x56, 0x45, 0x40, 0x50, 0xa2, 0x29, 0x06, 0x15, 0xd8, 0x7e, 0x4a, 0x81, 0x0f, 0xe0, 0xc8, 0xd8,
	0xdc, 0xf6, 0x86, 0x57, 0x2b, 0x94, 0x83, 0x47, 0x8c, 0x39, 0x2b, 0xe3, 0x6a, 0xee, 0x35, 0x00,
	0x07, 0x7d, 0x4d, 0x35, 0xef, 0x70, 0x3e, 0xfd, 0x3f, 0xce, 0xa3, 0x7b, 0x9c, 0xff, 0xe1, 0x41,
	0x44, 0x63, 0xbd, 0x43, 0xce, 0x5f, 0x1d, 0x70, 0x3e, 0x1b, 0x38, 0xa7, 0x26, 0x06, 0xaa, 0x5f,
	0xc3, 0x87, 0xe4, 0xf1, 0x1d, 0xb9, 0xe8, 0x2b, 0xab, 0x56, 0x65, 0x29, 0xd1, 0xf4, 0x95, 0xa5,
	0x1f, 0x96, 0x2a, 0xdd, 0x0b, 0x11, 0x4a, 0x32, 0xd7, 0x47, 0xfc, 0x6b, 0xfa, 0xea, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf7, 0x12, 0x83, 0x63, 0x1c, 0x07, 0x00, 0x00,
}
