mysql:
  dsn: "root:@tcp(127.0.0.1:3306)/mp?charset=utf8mb4&parseTime=True&loc=Local"
  debug: 1

redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  db: 0

session:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  db: 1

auth:
  skip: "true"

aes:
  key: "AbCdeF0912873465"